#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-x"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "39b88de5eb1c47ef80a55f1475373b74" }
]

[assets]
directory = "./public"
